import Link from 'next/link'
import './legal.css'

export default function LegalPage() {
  return (
    <div className="legal-page">
      <div className="legal-container">
        <Link href="/" className="legal-back">
          &larr; Back to Chronicle
        </Link>

        <h1 className="legal-title">Rechtliches</h1>
        <p className="legal-subtitle">(Legal)</p>

        <nav className="legal-nav">
          <a href="#tos-de">Nutzungsbedingungen (DE)</a>
          <a href="#tos-en">Terms of Service (EN)</a>
          <a href="#privacy-de">Datenschutz (DE)</a>
          <a href="#privacy-en">Privacy Policy (EN)</a>
        </nav>

        {/* Terms of Service - German */}
        <section id="tos-de" className="legal-section">
          <h2>Nutzungsbedingungen</h2>
          <p className="legal-date">Stand: Januar 2026</p>

          <h3>1. Geltungsbereich</h3>
          <p>Diese Nutzungsbedingungen gelten für die Nutzung der Plattform Chronicle, betrieben von MM FinTech UG (haftungsbeschränkt), Auguststraße 47A, 10119 Berlin.</p>

          <h3>2. Leistungsbeschreibung</h3>
          <p>Chronicle ist eine KI-basierte Plattform zur automatischen Erstellung von Büchern und Audiobooks. Die Inhalte werden durch künstliche Intelligenz generiert und können Text, Bilder (Cover) sowie Text-zu-Sprache-Audio umfassen.</p>

          <h3>3. Registrierung und Konto</h3>
          <ul>
            <li>Die Nutzung erfordert eine Registrierung über Google OAuth oder E-Mail</li>
            <li>Du bist für die Sicherheit deines Kontos verantwortlich</li>
            <li>Die Weitergabe von Zugangsdaten ist nicht gestattet</li>
          </ul>

          <h3>4. Nutzungsrechte an generierten Inhalten</h3>
          <ul>
            <li>Du erhältst das Recht, die für dich generierten Inhalte privat zu nutzen, zu teilen und zu exportieren</li>
            <li>Die kommerzielle Nutzung generierter Inhalte ist nur mit ausdrücklicher Genehmigung gestattet</li>
            <li>Chronicle behält sich das Recht vor, anonymisierte Nutzungsdaten zur Verbesserung des Dienstes zu verwenden</li>
          </ul>

          <h3>5. Verbotene Nutzung</h3>
          <p>Es ist untersagt, Chronicle zu nutzen für:</p>
          <ul>
            <li>Illegale, diskriminierende oder rechtsverletzende Inhalte</li>
            <li>Inhalte, die Rechte Dritter verletzen</li>
            <li>Automatisierte Massenabfragen oder Scraping</li>
            <li>Umgehung technischer Schutzmaßnahmen</li>
          </ul>

          <h3>6. KI-generierte Inhalte</h3>
          <ul>
            <li>Alle Inhalte werden von KI-Modellen erstellt und können Fehler oder Ungenauigkeiten enthalten</li>
            <li>Chronicle übernimmt keine Gewähr für Richtigkeit, Vollständigkeit oder Eignung der Inhalte</li>
            <li>Die Inhalte stellen keine professionelle Beratung dar</li>
          </ul>

          <h3>7. Verfügbarkeit</h3>
          <p>Chronicle wird nach bestem Bemühen bereitgestellt. Ein Anspruch auf ununterbrochene Verfügbarkeit besteht nicht. Wartungsarbeiten und Updates können zu vorübergehenden Einschränkungen führen.</p>

          <h3>8. Haftung</h3>
          <ul>
            <li>Die Haftung ist auf Vorsatz und grobe Fahrlässigkeit beschränkt</li>
            <li>Für mittelbare Schäden, entgangenen Gewinn oder Datenverlust wird nicht gehaftet</li>
            <li>Die Haftungsbeschränkungen gelten nicht für Schäden an Leben, Körper oder Gesundheit</li>
          </ul>

          <h3>9. Kündigung</h3>
          <p>Du kannst dein Konto jederzeit löschen. Chronicle behält sich das Recht vor, Konten bei Verstoß gegen diese Bedingungen zu sperren oder zu löschen.</p>

          <h3>10. Änderungen</h3>
          <p>Chronicle kann diese Bedingungen jederzeit ändern. Wesentliche Änderungen werden per E-Mail oder in der App mitgeteilt. Die weitere Nutzung nach Änderung gilt als Zustimmung.</p>

          <h3>11. Anwendbares Recht</h3>
          <p>Es gilt deutsches Recht. Gerichtsstand ist Berlin, soweit gesetzlich zulässig.</p>
        </section>

        <div className="legal-divider" />

        {/* Terms of Service - English */}
        <section id="tos-en" className="legal-section">
          <h2>Terms of Service</h2>
          <p className="legal-date">Last updated: January 2026</p>

          <h3>1. Scope</h3>
          <p>These Terms of Service apply to the use of the Chronicle platform, operated by MM FinTech UG (haftungsbeschränkt), Auguststraße 47A, 10119 Berlin, Germany.</p>

          <h3>2. Service Description</h3>
          <p>Chronicle is an AI-powered platform for automatic book and audiobook creation. Content is generated by artificial intelligence and may include text, images (covers), and text-to-speech audio.</p>

          <h3>3. Registration and Account</h3>
          <ul>
            <li>Use requires registration via Google OAuth or email</li>
            <li>You are responsible for the security of your account</li>
            <li>Sharing login credentials is not permitted</li>
          </ul>

          <h3>4. Rights to Generated Content</h3>
          <ul>
            <li>You receive the right to use, share, and export content generated for you for personal use</li>
            <li>Commercial use of generated content requires explicit permission</li>
            <li>Chronicle reserves the right to use anonymized usage data to improve the service</li>
          </ul>

          <h3>5. Prohibited Use</h3>
          <p>It is prohibited to use Chronicle for:</p>
          <ul>
            <li>Illegal, discriminatory, or rights-infringing content</li>
            <li>Content that violates third-party rights</li>
            <li>Automated bulk requests or scraping</li>
            <li>Circumventing technical protection measures</li>
          </ul>

          <h3>6. AI-Generated Content</h3>
          <ul>
            <li>All content is created by AI models and may contain errors or inaccuracies</li>
            <li>Chronicle does not warrant the accuracy, completeness, or fitness of content</li>
            <li>Content does not constitute professional advice</li>
          </ul>

          <h3>7. Availability</h3>
          <p>Chronicle is provided on a best-effort basis. There is no guarantee of uninterrupted availability. Maintenance and updates may cause temporary disruptions.</p>

          <h3>8. Liability</h3>
          <ul>
            <li>Liability is limited to intent and gross negligence</li>
            <li>No liability for indirect damages, lost profits, or data loss</li>
            <li>Liability limitations do not apply to damages to life, body, or health</li>
          </ul>

          <h3>9. Termination</h3>
          <p>You may delete your account at any time. Chronicle reserves the right to suspend or delete accounts that violate these terms.</p>

          <h3>10. Changes</h3>
          <p>Chronicle may change these terms at any time. Material changes will be communicated via email or in-app notification. Continued use after changes constitutes acceptance.</p>

          <h3>11. Governing Law</h3>
          <p>German law applies. The place of jurisdiction is Berlin, to the extent permitted by law.</p>
        </section>

        <div className="legal-divider" />

        {/* Privacy Policy - German */}
        <section id="privacy-de" className="legal-section">
          <h2>Datenschutzerklärung</h2>

          <h3>1. Verantwortlicher</h3>
          <p>Verantwortlich im Sinne der Datenschutz-Grundverordnung (DSGVO):</p>
          <div className="legal-address">
            <p><strong>MM FinTech UG (haftungsbeschränkt)</strong></p>
            <p>handelnd unter der Marke Chronicle</p>
            <p>Auguststraße 47A</p>
            <p>10119 Berlin</p>
            <p>Deutschland</p>
            <p>E-Mail: info@chronicle.town</p>
          </div>

          <h3>2. Beschreibung des Dienstes</h3>
          <p>Chronicle ist eine KI-basierte Plattform zur automatischen Erstellung, Personalisierung und Wiedergabe von Büchern, einschließlich Text-zu-Sprache-Funktionen (Audiobooks). Die Inhalte werden überwiegend automatisiert durch KI-Modelle erzeugt, verarbeitet und bereitgestellt.</p>

          <h3>3. Verarbeitete Daten</h3>

          <h4>a) Nutzungs- und Zugriffsdaten</h4>
          <ul>
            <li>IP-Adresse (gekürzt/anonymisiert, sofern möglich)</li>
            <li>Datum, Uhrzeit und Dauer der Nutzung</li>
            <li>Gerätetyp, Betriebssystem, Browser</li>
            <li>Fehler- und Performance-Logs</li>
          </ul>
          <p><strong>Zweck:</strong> Sicherer Betrieb, Stabilität und Optimierung der Plattform</p>
          <p><strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse)</p>

          <h4>b) Inhalts- und Interaktionsdaten</h4>
          <ul>
            <li>Texteingaben oder Auswahlparameter (z. B. Genre, Stil, Länge)</li>
            <li>Automatisch generierte Buch- und Audiobook-Inhalte</li>
            <li>Nutzungspräferenzen (z. B. Lese- oder Hörfortschritt)</li>
          </ul>
          <p><strong>Zweck:</strong> Bereitstellung und Personalisierung des Dienstes</p>
          <p><strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung)</p>

          <h4>c) Audio- &amp; Text-zu-Sprache-Daten</h4>
          <p>Bei Nutzung der Hörfunktion werden Texte automatisiert an Text-to-Speech-Dienste übermittelt.</p>
          <ul>
            <li>Es erfolgt keine Sprachaufnahme des Nutzers</li>
            <li>Verarbeitet wird ausschließlich Text</li>
          </ul>
          <p><strong>Zweck:</strong> Erstellung von Audiobooks</p>
          <p><strong>Rechtsgrundlage:</strong> Art. 6 Abs. 1 lit. b DSGVO</p>

          <h3>4. Einsatz von KI-Modellen &amp; Auftragsverarbeitern</h3>
          <p>Chronicle nutzt externe Dienstleister für:</p>
          <ul>
            <li>Textgenerierung (KI-Modelle)</li>
            <li>Audiogenerierung (Text-to-Speech)</li>
            <li>Hosting &amp; Infrastruktur</li>
          </ul>
          <p><strong>Wichtige Hinweise:</strong></p>
          <ul>
            <li>Inhalte werden nicht öffentlich zugänglich gemacht</li>
            <li>Es erfolgt keine werbliche Nutzung der Daten</li>
            <li>Personenbezogene Daten werden nach Möglichkeit vermieden, anonymisiert oder pseudonymisiert</li>
            <li>Verarbeitung erfolgt im Rahmen von Auftragsverarbeitungsverträgen gemäß Art. 28 DSGVO</li>
          </ul>

          <h3>5. Speicherdauer &amp; Löschung</h3>
          <ul>
            <li>Daten werden nur so lange gespeichert, wie es für den jeweiligen Zweck erforderlich ist</li>
            <li>Technische Protokolle werden regelmäßig gelöscht</li>
            <li>Nutzer können jederzeit die Löschung ihrer Inhalte verlangen</li>
          </ul>

          <h3>6. Cookies &amp; lokale Speichertechnologien</h3>
          <p>Chronicle verwendet ausschließlich:</p>
          <ul>
            <li>technisch notwendige Cookies</li>
            <li>lokale Speichermechanismen (z. B. Local Storage)</li>
          </ul>
          <p><strong>Keine Nutzung von:</strong></p>
          <ul>
            <li>Tracking-Cookies</li>
            <li>Werbe- oder Marketing-Cookies</li>
          </ul>
          <p><strong>Rechtsgrundlage:</strong> § 25 Abs. 2 TTDSG, Art. 6 Abs. 1 lit. f DSGVO</p>

          <h3>7. Rechte der betroffenen Personen</h3>
          <p>Du hast jederzeit das Recht auf:</p>
          <ul>
            <li>Auskunft (Art. 15 DSGVO)</li>
            <li>Berichtigung (Art. 16 DSGVO)</li>
            <li>Löschung (Art. 17 DSGVO)</li>
            <li>Einschränkung der Verarbeitung (Art. 18 DSGVO)</li>
            <li>Datenübertragbarkeit (Art. 20 DSGVO)</li>
            <li>Widerspruch (Art. 21 DSGVO)</li>
          </ul>
          <p>Anfragen bitte an: info@chronicle.town</p>

          <h3>8. Beschwerderecht</h3>
          <p>Du hast das Recht, dich bei einer Datenschutzaufsichtsbehörde zu beschweren. Zuständig ist u. a. der Berliner Beauftragte für Datenschutz und Informationsfreiheit.</p>

          <h3>9. Datensicherheit</h3>
          <p>Wir setzen angemessene technische und organisatorische Maßnahmen ein, darunter:</p>
          <ul>
            <li>TLS-Verschlüsselung</li>
            <li>Zugriffsbeschränkungen</li>
            <li>Datensparsamkeit</li>
            <li>Trennung von Inhalts- und Systemdaten</li>
          </ul>

          <h3>10. Änderungen dieser Datenschutzerklärung</h3>
          <p>Wir behalten uns vor, diese Datenschutzerklärung bei technischen oder rechtlichen Änderungen anzupassen. Die jeweils aktuelle Version ist unter chronicle.town abrufbar.</p>
        </section>

        <div className="legal-divider" />

        {/* Privacy Policy - English */}
        <section id="privacy-en" className="legal-section">
          <h2>Privacy Policy</h2>

          <h3>1. Controller</h3>
          <p>The controller within the meaning of the GDPR is:</p>
          <div className="legal-address">
            <p><strong>MM FinTech UG (haftungsbeschränkt)</strong></p>
            <p>operating under the brand Chronicle</p>
            <p>Auguststraße 47A</p>
            <p>10119 Berlin</p>
            <p>Germany</p>
            <p>E-mail: info@chronicle.town</p>
          </div>

          <h3>2. Description of the Service</h3>
          <p>Chronicle is an AI-powered platform for the automatic creation, personalization, and playback of books, including text-to-speech audiobook functionality. Content is largely generated and processed automatically by AI models.</p>

          <h3>3. Data Processed</h3>

          <h4>a) Usage and Access Data</h4>
          <ul>
            <li>IP address (anonymized where possible)</li>
            <li>Date, time, and duration of use</li>
            <li>Device type, operating system, browser</li>
            <li>Error and performance logs</li>
          </ul>
          <p><strong>Purpose:</strong> Operation, security, and optimization of the platform</p>
          <p><strong>Legal basis:</strong> Art. 6(1)(f) GDPR (legitimate interest)</p>

          <h4>b) Content and Interaction Data</h4>
          <ul>
            <li>Text inputs or configuration parameters</li>
            <li>AI-generated books and audiobooks</li>
            <li>Usage preferences (e.g. reading or listening progress)</li>
          </ul>
          <p><strong>Purpose:</strong> Provision and personalization of the service</p>
          <p><strong>Legal basis:</strong> Art. 6(1)(b) GDPR (contract performance)</p>

          <h4>c) Text-to-Speech Data</h4>
          <p>For audiobook playback, text is transmitted to text-to-speech providers.</p>
          <ul>
            <li>No voice recordings of users are made</li>
            <li>Only text data is processed</li>
          </ul>
          <p><strong>Purpose:</strong> Audiobook generation</p>
          <p><strong>Legal basis:</strong> Art. 6(1)(b) GDPR</p>

          <h3>4. Use of AI Models &amp; Processors</h3>
          <p>Chronicle uses external providers for:</p>
          <ul>
            <li>AI text generation</li>
            <li>Text-to-speech services</li>
            <li>Hosting and infrastructure</li>
          </ul>
          <p><strong>Key principles:</strong></p>
          <ul>
            <li>No public disclosure of user content</li>
            <li>No advertising use of data</li>
            <li>Personal data is minimized or anonymized where possible</li>
            <li>Processing is governed by data processing agreements under Art. 28 GDPR</li>
          </ul>

          <h3>5. Data Retention &amp; Deletion</h3>
          <ul>
            <li>Data is stored only as long as necessary</li>
            <li>Technical logs are deleted regularly</li>
            <li>Users may request deletion of their content at any time</li>
          </ul>

          <h3>6. Cookies &amp; Local Storage</h3>
          <p>Chronicle uses only:</p>
          <ul>
            <li>technically necessary cookies</li>
            <li>local storage mechanisms</li>
          </ul>
          <p>No tracking or advertising cookies are used.</p>
          <p><strong>Legal basis:</strong> Section 25(2) TTDSG, Art. 6(1)(f) GDPR</p>

          <h3>7. Your Rights</h3>
          <p>You have the right to:</p>
          <ul>
            <li>Access (Art. 15 GDPR)</li>
            <li>Rectification (Art. 16 GDPR)</li>
            <li>Erasure (Art. 17 GDPR)</li>
            <li>Restriction of processing (Art. 18 GDPR)</li>
            <li>Data portability (Art. 20 GDPR)</li>
            <li>Object to processing (Art. 21 GDPR)</li>
          </ul>
          <p>Contact: info@chronicle.town</p>

          <h3>8. Right to Lodge a Complaint</h3>
          <p>You have the right to lodge a complaint with a supervisory authority, in particular the Berlin Commissioner for Data Protection and Freedom of Information.</p>

          <h3>9. Data Security</h3>
          <p>We implement appropriate technical and organizational measures, including:</p>
          <ul>
            <li>Encrypted connections (TLS)</li>
            <li>Access controls</li>
            <li>Data minimization</li>
            <li>Separation of content and system data</li>
          </ul>

          <h3>10. Changes to this Privacy Policy</h3>
          <p>We may update this Privacy Policy to reflect technical or legal changes. The current version is available at chronicle.town.</p>
        </section>

        <footer className="legal-footer">
          <Link href="/" className="legal-back">
            &larr; Back to Chronicle
          </Link>
        </footer>
      </div>
    </div>
  )
}
